baseURL : https://2018yfb1004800.cn/
languageCode : zh-cn
title : 人机物融合的云计算架构与平台
theme: hugo-refresh

disableKinds: ["sitemap","RSS"]

blackfriday:
  hrefTargetBlank: true

Taxonomies:
  tag: "tags"


# Supported fonts are:
# https://fonts.google.com/

params:
  # parameter used to specify if you want to minify the imported js
  jsMinify: false
  # parameter used to specify if you want to add the fingerprint to the imported js
  jsFingerprint: false
  # parameter used to specify if you want to minify the imported css
  cssMinify: true
  # parameter used to specify if you want to add the fingerprint to the imported css
  cssFingerprint: true
  # option to specify the main colour of the theme
  mainColour: "#F39200"

  # summary options
  summary:
    # option to specify the default image in the summary list
    defaultImage : "/images/title.png"
  
  # loading options
  loading:
    # option to specify the loading image
    image: "/images/rings.svg"

  # main pages options
  mainPage:
    # option to specify the main font of the theme
    fontFamily: "Open Sans" 

  # sidebar options
  sidebar:
    # option to specify the logo of the sidebar
    logo: "/images/refresh-square.svg"
    # option to specify the font of the sidebar
    fontFamily: "Open Sans" # "Open Sans"

  # navbar options
  navbar:
    # option to specify the logo of the sidebar
    fontFamily: "Open Sans"
  
  # 404 page options
  pagNotFound:
    # option to specify the main picture of the sidebar
    image: "/images/avataaars_404.png"
    # option to specify the title of the 404 page
    title: 404 Page Not Found :(
    # option to specify the subtitle of the 404 page
    subtitle: This is not the page you were looking for...
    # option to specify the width of the image in the 404 page
    imageWidth: 500px

  # homepage options
  homepage:
    # option to specify the title in the homepage
    title: 人机物融合的云计算架构与平台
    # option to specify the subtitle in the homepage
    subtitle: 国家重点研发项目《人机物融合的云计算架构与平台》信息发布网站
    # option to specify image in the homepage
    image: "/images/title.png" # worker.svg 
    # option to specify the width of the image in the homepage
    imageWidth: 400px

  # footer options
  footer:
    # option to specify the logo in the footer
    logo: "/images/refresh-square.svg"
    # option to specify your contact email in the footer
    email: name.surname@domain.com
    # option to specify your linkedin profile in the footer
    linkedin: https://2018yfb1004800.cn
    # option to specify the copyright in the footer
    copyright: 人机物融合的云计算架构与平台项目组
